# Geliştirme ortamı için Docker imajı
FROM node:14

# Çalışma dizini oluştur
WORKDIR /app

# package.json ve package-lock.json dosyalarını kopyala
COPY package*.json ./

# Bağımlılıkları yükle
RUN npm install

npm audit fix


# Uygulama kodunu kopyala
COPY . .

# Uygulamayı çalıştır
CMD ["npm", "run", "dev"]
